apiVersion: v1
kind: Service
metadata:
  name: compair-mysql
  labels:
    app: compair
spec:
  ports:
    - port: 3306
  selector:
    app: compair
    tier: mysql

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compair-mysql
  labels:
    app: compair
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: compair
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.1
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        - name: MYSQL_DATABASE
          value: compair
        - name: MYSQL_USER
          value: compair
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
