apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    app: compair
    tier: filestore
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: REPLACE_WITH_NFS_SERVICE_IP
    path: "/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
  labels:
    app: compair
    tier: filestore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: compair
      tier: filestore

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: gce-slow
  labels:
    app: compair
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: gce-slow
  labels:
    app: compair
    tier: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi